name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Jekyll
        uses: helaili/jekyll-action@v2

      - name: Build and Deploy
        run: |
          bundle install
          bundle exec jekyll build -d _site
          git config --global user.email "luzodj123789@gmail.com"
          git config --global user.name "Jared Luzod"
          git add .
          git commit -m "Deploy site"
          git push
